name: Update LOC in README

on:
  schedule:
    - cron: '0 0 */3 * *' # every 3 days
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.PAT }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tokei jq gh git

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< $GH_TOKEN

      - name: Clone all repos
        run: |
          mkdir repos && cd repos
          gh repo list KaranMali2001 --limit 200 --json nameWithOwner -q '.[].nameWithOwner' \
          | xargs -L1 -I{} gh repo clone {} .

      - name: Count lines
        run: tokei --output json repos > loc.json

      - name: Generate LOC summary
        run: |
          total=$(jq '[.languages[].code] | add' loc.json)
          jq '.languages | to_entries | map("- \(.key): \(.value.code)") | . + ["- Total: '"$total"'"] | join("\n")' -r loc.json > LOC.md

      - name: Update README
        run: |
          awk '/<!--LOC_START-->/ {print; system("cat LOC.md"); found=1; next} /<!--LOC_END-->/ {found=0} !found' README.md > README_new.md
          mv README_new.md README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update LOC stats" || echo "No changes to commit"
          git push
